apiVersion: v1
kind: Service
metadata:
  name: recreate-svc
  namespace: recreate-demo
  labels:
    app: recreate-demo
spec:
  type: ClusterIP
  selector:
    app: recreate-demo
  ports:
    - name: http
      port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-demo
  namespace: recreate-demo
  labels:
    app: recreate-demo
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recreate-demo
  template:
    metadata:
      labels:
        app: recreate-demo
        version: v1
    spec:
      containers:
        - name: recreate-demo
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Recreate deployment version v1"
          ports:
            - containerPort: 5678
