apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weighted-cert
  namespace: weighted
  labels:
    # Must match the selector in ClusterIssuer solver for weighted
    solver: weighted
spec:
  secretName: weighted-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - weighted.tagent.cfd
