apiVersion: apps/v1
kind: Deployment
metadata:
  name: disney-hotstar-app
  labels:
    app: disney-hotstar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: disney-hotstar-app
  template:
    metadata:
      labels:
        app: disney-hotstar-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: disney-hotstar-app
        image: veeranarni/hotstar:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
