apiVersion: v1
kind: Service
metadata:
  name: disney-hotstar-app
  labels:
    app: disney-hotstar-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: disney-hotstar-app
