apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hpa   # Name of deployment
  namespace: default
spec:
  replicas: 1       # Start with 1 pod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx   # Label used by service & HPA
    spec:
      containers:
      - name: nginx
        image: nginx:latest  
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"   # Minimum CPU required (IMPORTANT for HPA)
          limits:
            cpu: "500m"   # Max CPU allowed
