apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v2
  namespace: canary-demo
  labels:
    app: canary-demo
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-demo
      version: v2
  template:
    metadata:
      labels:
        app: canary-demo
        version: v2
    spec:
      containers:
        - name: canary-v2
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Canary deployment version v2"
          ports:
            - containerPort: 5678
