apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: canary-demo
  labels:
    app: canary-demo
spec:
  type: ClusterIP
  selector:
    app: canary-demo
  ports:
    - name: http
      port: 80
      targetPort: 5678
