apiVersion: v1
kind: Service
metadata:
  name: rolling-svc
  namespace: rolling-demo
  labels:
    app: rolling-demo
spec:
  type: ClusterIP
  selector:
    app: rolling-demo
  ports:
    - name: http
      port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-demo
  namespace: rolling-demo
  labels:
    app: rolling-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: rolling-demo
  template:
    metadata:
      labels:
        app: rolling-demo
        version: v1
    spec:
      containers:
        - name: rolling-demo
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Rolling update version v1"
          ports:
            - containerPort: 5678
