// All videos — no API key needed
const videos = [
    {
        videoId: "xnL-8iskVJA",
        title: "From Zero to Production Deploy Fullstack App on AWS ECS Fargate (Real Project)",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/xnL-8iskVJA/mqdefault.jpg",
        publishedAt: "2024-01-15",
        type: "video",
    },
    {
        videoId: "cEmwmkEWVzA",
        title: "Deploy a real production-ready Fullstack Bookstore Application to AWS EKS (Kubernetes) from scratch",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/cEmwmkEWVzA/mqdefault.jpg",
        publishedAt: "2024-02-10",
        type: "video",
    },
    {
        videoId: "bh_BXfl9lKs",
        title: "5 Microservices Real-World Project: Multi-Language, Multi-DB on Kubernetes EKS + Terraform + ArgoCD",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/bh_BXfl9lKs/mqdefault.jpg",
        publishedAt: "2024-03-05",
        type: "video",
    },
    {
        videoId: "eVLDcytN8tA",
        title: "Swiggy Clone CI/CD on AWS EKS with GitOps, ArgoCD, Jenkins, Terraform | Full DevOps Project",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/eVLDcytN8tA/mqdefault.jpg",
        publishedAt: "2024-03-20",
        type: "video",
    },
    {
        videoId: "5PeEFaz22-4",
        title: "Deploy Hotstar Clone with DevSecOps, GitOps & Kubernetes | Full CI/CD Pipeline Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/5PeEFaz22-4/mqdefault.jpg",
        publishedAt: "2024-04-01",
        type: "video",
    },
    {
        videoId: "K94d3nuk4Kw",
        title: "Build a Serverless Web Form Using AWS API Gateway, Lambda & DynamoDB | Step-by-Step Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/K94d3nuk4Kw/mqdefault.jpg",
        publishedAt: "2024-04-15",
        type: "video",
    },
    {
        videoId: "N9JqIV7eM-8",
        title: "11 Microservice CICD Pipeline DevOps Project | E-Commerce Application | #DevOps #AWS #Microservices",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/N9JqIV7eM-8/mqdefault.jpg",
        publishedAt: "2024-05-01",
        type: "video",
    },
    {
        videoId: "DiHmHEXyAlk",
        title: "How to Migrate Databases from EC2 to RDS with AWS DMS | Beginner-Friendly Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/DiHmHEXyAlk/mqdefault.jpg",
        publishedAt: "2024-05-15",
        type: "video",
    },
    {
        videoId: "Vy4tZ5D0Iv8",
        title: "CI/CD with Jenkins, ArgoCD & Kubernetes | Java Project | GitOps Workflow Explained (Part-2)",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/Vy4tZ5D0Iv8/mqdefault.jpg",
        publishedAt: "2024-06-01",
        type: "video",
    },
    {
        videoId: "26rjNPHukrA",
        title: "Maven + Jenkins CI/CD Pipeline with Docker | Step-by-Step DevOps Java Project Tutorial | Part-1",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/26rjNPHukrA/mqdefault.jpg",
        publishedAt: "2024-06-15",
        type: "video",
    },
    {
        videoId: "h45-o8q9Vno",
        title: "Build an AI Chatbot with Amazon Bedrock and S3 | RAG for Better Answers",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/h45-o8q9Vno/mqdefault.jpg",
        publishedAt: "2024-07-01",
        type: "video",
    },
    {
        videoId: "NjGLfkSft-w",
        title: "Amazon S3 Vectors Explained | Native Vector Store for AI, Semantic Search & RAG",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/NjGLfkSft-w/mqdefault.jpg",
        publishedAt: "2024-07-10",
        type: "video",
    },
    {
        videoId: "BS7a7V5eGas",
        title: "OpenShift Explained: The Most Popular Kubernetes Platform Used by Organizations | Project Demo",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/BS7a7V5eGas/mqdefault.jpg",
        publishedAt: "2024-07-20",
        type: "video",
    },
    {
        videoId: "rVmCqup6Ibk",
        title: "Red Hat OpenShift Trial Setup on Developer Sandbox | Easy Installation Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/rVmCqup6Ibk/mqdefault.jpg",
        publishedAt: "2024-08-01",
        type: "video",
    },
    {
        videoId: "ws_WewO6tnA",
        title: "Session - 1 | SRE Basics Explained: Observability, Metrics, Logs & Traces for Beginners | #sre",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/ws_WewO6tnA/mqdefault.jpg",
        publishedAt: "2024-08-10",
        type: "video",
    },
    {
        videoId: "lUBkMht_Fxc",
        title: "Session -2 | SRE Metrics Explained: Everything You Need to Know About Monitoring & Observability",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/lUBkMht_Fxc/mqdefault.jpg",
        publishedAt: "2024-08-20",
        type: "video",
    },
    {
        videoId: "-cHHmU6Phqw",
        title: "Build Python Flask Backend with Amazon RDS MySQL on AWS | EC2 API Server Full Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/-cHHmU6Phqw/mqdefault.jpg",
        publishedAt: "2024-09-01",
        type: "video",
    },
    {
        videoId: "J5YAG6EnG7Y",
        title: "AWS Lambda Connect to RDS Securely using Secrets Manager | Full Hands-On DevOps Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/J5YAG6EnG7Y/mqdefault.jpg",
        publishedAt: "2024-09-10",
        type: "video",
    },
    {
        videoId: "vxgHx5uo-Yw",
        title: "AWS Lambda + Amazon RDS MySQL | Serverless Database Connection | Step-by-Step Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/vxgHx5uo-Yw/mqdefault.jpg",
        publishedAt: "2024-09-20",
        type: "video",
    },
    {
        videoId: "Md30cAJnFRc",
        title: "Production Grade AWS Logging Pipeline (EC2 → CloudWatch → Lambda → S3)",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/Md30cAJnFRc/mqdefault.jpg",
        publishedAt: "2024-10-01",
        type: "video",
    },
    {
        videoId: "Us3A1ItCfcw",
        title: "Deploy Full Stack App on AWS in 10 Minutes | Elastic Beanstalk Complete Guide (Live Demo)",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/Us3A1ItCfcw/mqdefault.jpg",
        publishedAt: "2024-10-10",
        type: "video",
    },
    {
        videoId: "PLvHthQctBM",
        title: "Deploy a JavaScript Memory Game to AWS S3 with CodePipeline | Full CI/CD Tutorial",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/PLvHthQctBM/mqdefault.jpg",
        publishedAt: "2024-10-20",
        type: "video",
    },
    {
        videoId: "DYzpfWiOq5E",
        title: "Multi S3 Static Website with CloudFront & Lambda Cache Invalidation | Video 3",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/DYzpfWiOq5E/mqdefault.jpg",
        publishedAt: "2024-11-01",
        type: "video",
    },
    {
        videoId: "GAU_oJMSs8M",
        title: "S3 Static Website Hosting with CloudFront | AWS Project | Video 2",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/GAU_oJMSs8M/mqdefault.jpg",
        publishedAt: "2024-11-10",
        type: "video",
    },
    {
        videoId: "qzDPwGAN52Y",
        title: "CloudFront with Application Load Balancer | AWS Architecture Explained | Video 1",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/qzDPwGAN52Y/mqdefault.jpg",
        publishedAt: "2024-11-20",
        type: "video",
    },
    {
        videoId: "G_v87Rv0El8",
        title: "How Real Companies Manage AWS Access | AWS SSO, Roles & Governance",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/G_v87Rv0El8/mqdefault.jpg",
        publishedAt: "2024-12-01",
        type: "video",
    },
    {
        videoId: "3CnBZNjq9zg",
        title: "Build an AI Image Editing App on AWS Using Bedrock (Serverless Full Stack Project)",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/3CnBZNjq9zg/mqdefault.jpg",
        publishedAt: "2024-12-10",
        type: "video",
    },
    {
        videoId: "ilc9JSEuRtw",
        title: "Session-1 | Kubernetes Architecture Explained Clearly | Complete Beginner to Advanced Foundation",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/ilc9JSEuRtw/mqdefault.jpg",
        publishedAt: "2025-01-01",
        type: "video",
    },
    {
        videoId: "v6i1LkuWSyE",
        title: "Session-2 | ECS Cluster Deployment Using Terraform (Production Level) | Worker Nodes Explained",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/v6i1LkuWSyE/mqdefault.jpg",
        publishedAt: "2025-01-10",
        type: "video",
    },
    {
        videoId: "B_neA2w-gCs",
        title: "Session-3 | Kubernetes Services Explained (ClusterIP, NodePort, LoadBalancer) | Full Hands-On Lab",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/B_neA2w-gCs/mqdefault.jpg",
        publishedAt: "2025-01-20",
        type: "video",
    },
    {
        videoId: "hiv1cnD8_ao",
        title: "Session-4 | Kubernetes Autoscaling Explained | HPA vs VPA Hands-On Demo",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/hiv1cnD8_ao/mqdefault.jpg",
        publishedAt: "2025-02-01",
        type: "video",
    },
    {
        videoId: "aYR8Lki5478",
        title: "Session-5 | Kubernetes Namespaces Explained | Dev vs QA vs Prod in One Cluster (Hands-on)",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/aYR8Lki5478/mqdefault.jpg",
        publishedAt: "2025-02-10",
        type: "video",
    },
    {
        videoId: "WNDKD59hNpo",
        title: "Section 6.1 | Kubernetes Ingress on AWS EKS | ALB Controller + HTTPS + Real Domain | Full Guide",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/WNDKD59hNpo/mqdefault.jpg",
        publishedAt: "2025-02-20",
        type: "video",
    },
];

// Shorts / Reels
const shorts = [
    {
        videoId: "_T4DUZEJaX8",
        title: "Devops project #devopsprojects",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/_T4DUZEJaX8/mqdefault.jpg",
        publishedAt: "2024-06-01",
        type: "short",
    },
    {
        videoId: "KRz_w03meTU",
        title: "Deploy a real production ready Fullstack Bookstore Application to AWS EKS Kubernetes from scratch",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/KRz_w03meTU/mqdefault.jpg",
        publishedAt: "2024-06-10",
        type: "short",
    },
    {
        videoId: "T_c2lS95WsQ",
        title: "ONLYOFFICE at DevConf.IN 🚀 | Insights by Eeshaan Sawant",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/T_c2lS95WsQ/mqdefault.jpg",
        publishedAt: "2024-07-01",
        type: "short",
    },
    {
        videoId: "jBYYc1-pQBY",
        title: "ONLYOFFICE + AI at DevConf.IN | Smarter Document Generation",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/jBYYc1-pQBY/mqdefault.jpg",
        publishedAt: "2024-07-05",
        type: "short",
    },
    {
        videoId: "TMYuRmfC6z0",
        title: "Fedora Project Community Corner at DevConf.IN 2026 | Insights by Akashdeep Dhar",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/TMYuRmfC6z0/mqdefault.jpg",
        publishedAt: "2024-07-10",
        type: "short",
    },
    {
        videoId: "Lu-Wjqh6xR8",
        title: "FreeIPA Insights from DevConf | Identity Management & Security",
        channel: "Yaswanth Arumulla",
        thumbnail: "https://img.youtube.com/vi/Lu-Wjqh6xR8/mqdefault.jpg",
        publishedAt: "2024-07-15",
        type: "short",
    },
];

export { videos, shorts };
export default videos;
