apiVersion: v1
kind: Pod
metadata:
  name: secret-missing-pod
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: missing-secret   # ❌ Secret not found
              key: password

