apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-green
  namespace: bluegreen-demo
  labels:
    app: blue-green-app
    color: green
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green-app
      color: green
  template:
    metadata:
      labels:
        app: blue-green-app
        color: green
        version: v1
    spec:
      containers:
        - name: blue-green-green
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Blue Green deployment GREEN version v1"
          ports:
            - containerPort: 5678
