apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-blue
  namespace: bluegreen-demo
  labels:
    app: blue-green-app
    color: blue
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green-app
      color: blue
  template:
    metadata:
      labels:
        app: blue-green-app
        color: blue
        version: v2
    spec:
      containers:
        - name: blue-green-blue
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=Blue Green deployment BLUE version v2"
          ports:
            - containerPort: 5678
