apiVersion: v1
kind: Service
metadata:
  name: blue-green-svc
  namespace: bluegreen-demo
  labels:
    app: blue-green-app
spec:
  type: ClusterIP
  selector:
    app: blue-green-app
    color: green
  ports:
    - name: http
      port: 80
      targetPort: 5678
