apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traffic-splitting-cert
  namespace: traffic-splitting
  labels:
    # Must match the selector in ClusterIssuer solver for traffic-splitting
    solver: traffic
spec:
  secretName: traffic-splitting-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - traffic-splitting.tagent.cfd
