apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paytam-cert
  namespace: paytam
  labels:
    # Must match the selector in ClusterIssuer solver for paytam
    solver: paytam
spec:
  secretName: paytam-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - paytam.tagent.cfd
