apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hamster-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hamster   # Target deployment

  updatePolicy:
    updateMode: "Recreate"   # Restart pod to apply new resources
    minReplicas: 2

  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      
      # Minimum allowed resources
      minAllowed:
        cpu: 100m
        memory: 50Mi
      
      # Maximum allowed resources
      maxAllowed:
        cpu: "1"
        memory: 500Mi
      
      controlledResources:
      - cpu
      - memory
