apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: paytam-gateway
  namespace: url-rewrite
spec:
  gatewayClassName: gateway-api
  listeners:
    - name: http
      protocol: HTTP
      port: 80
